version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - enabledelayedexpansion
  - enableextensions
  - errorlevel
  - healthindicator
  - Metaspace
  - popd
  - pushd
  - setlocal
ignoreWords: []
import: []
