version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - bootstarp
  - enabledelayedexpansion
  - enableextensions
  - errorlevel
  - esbuild
  - gradlew
  - healthindicator
  - Metaspace
  - passay
  - popd
  - pushd
  - setlocal
ignoreWords: []
import: []
