server:
  port: 9090

spring:
  application:
    name: jdbc-default-authentication
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:h2:mem:sbipdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      "[hibernate.format_sql]": true
  devtools:
    # 💡기본값(true)이면 자동으로 다음에 명시된 프로퍼티를 추가하는데, 필요한 것만 명시적으로 수동 추가한다.
    # https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-devtools/src/main/resources/org/springframework/boot/devtools/env/devtools-property-defaults.properties
    add-properties: false
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
      chain:
        cache: false
  ldap:
    # LDAP 클라이언트 설정
    base: dc=manning,dc=com
    urls:
      - ldap://localhost:8389
    # LDAP 임베디드 서버 설정
    embedded:
      port: 8389
      ldif: classpath:users.ldif
      base-dn: dc=manning,dc=com


logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} [%thread] %clr(%-5level) %clr(%logger{72}){cyan} - %msg%n"
  level:
    root: info
    web: debug
    "[org.springboot.practice]": debug
    "[org.hibernate.orm.jdbc.bind]": trace
    # "[org.hibernate.orm.jdbc.extract]": trace
