spring:
  application:
    name: custom-failure-analyzer

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} [%thread] %clr(%-5level) %clr(%logger{72}){cyan} - %msg%n"
  level:
    root: info
    web: debug
    "[org.springboot.practice]": debug
    "[org.hibernate.orm.jdbc.bind]": trace
    # "[org.hibernate.orm.jdbc.extract]": trace

# External API URL
api.url: https://dog.ceo/dog-api/
