spring:
  application:
    name: custom-healthindicator

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} [%thread] %clr(%-5level) %clr(%logger{72}){cyan} - %msg%n"
  level:
    root: info
    web: debug
    "[org.springboot.practice]": debug

management:
  endpoint:
    health:
      show-details: always
  server:
    port: 8081
