spring:
  application:
    name: custom-endpoint
  jmx:
    enabled: true

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} [%thread] %clr(%-5level) %clr(%logger{72}){cyan} - %msg%n"
  level:
    root: info
    web: debug
    "[org.springboot.practice]": debug

management:
  endpoints:
    web:
      exposure:
        include: # Expose the /releaseNotes actuator endpoint over HTTP
          - releaseNotes
    jmx:
      exposure:
        include:
          - releaseNotes
