spring:
  application:
    name: command-line-runner

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} [%thread] %clr(%-5level) %clr(%logger{72}){cyan} - %msg%n"
  level:
    root: info
    web: debug
    "[org.springboot.practice]": debug
