DROP TABLE IF EXISTS COURSES;
CREATE TABLE COURSES
(
    ID          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    NAME        VARCHAR(255),
    CATEGORY    VARCHAR(255),
    RATING      INT NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRIMARY KEY (ID)
);


DROP TABLE IF EXISTS authorities;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    username VARCHAR(50)  NOT NULL PRIMARY KEY,
    password VARCHAR(500) NOT NULL,
    enabled  BOOLEAN      NOT NULL
);

CREATE TABLE AUTHORITIES
(
    username  VARCHAR(50) NOT NULL,
    authority VARCHAR(50) NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES users (username)
);

CREATE UNIQUE INDEX ix_auth_username ON authorities (username, authority);
